// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One presentable RGBA frame plus chrome needed for input routing.
class RasterPresentFrame {
  final int width;
  final int height;

  /// Packed RGBA8888, row-major, length `width * height * 4`.
  final Uint8List rgba;
  final int cursorLine;
  final int cursorCol;
  final bool cursorVisible;
  final int cursorShape;
  final bool cursorBlinking;
  final int modeFlags;
  final int displayOffset;
  final int historySize;
  final double scrollFraction;
  final int defaultFg;
  final int defaultBg;
  final int cursorColor;

  /// True when the whole buffer was rebuilt (resize / full damage).
  final bool full;

  const RasterPresentFrame({
    required this.width,
    required this.height,
    required this.rgba,
    required this.cursorLine,
    required this.cursorCol,
    required this.cursorVisible,
    required this.cursorShape,
    required this.cursorBlinking,
    required this.modeFlags,
    required this.displayOffset,
    required this.historySize,
    required this.scrollFraction,
    required this.defaultFg,
    required this.defaultBg,
    required this.cursorColor,
    required this.full,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      rgba.hashCode ^
      cursorLine.hashCode ^
      cursorCol.hashCode ^
      cursorVisible.hashCode ^
      cursorShape.hashCode ^
      cursorBlinking.hashCode ^
      modeFlags.hashCode ^
      displayOffset.hashCode ^
      historySize.hashCode ^
      scrollFraction.hashCode ^
      defaultFg.hashCode ^
      defaultBg.hashCode ^
      cursorColor.hashCode ^
      full.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RasterPresentFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba &&
          cursorLine == other.cursorLine &&
          cursorCol == other.cursorCol &&
          cursorVisible == other.cursorVisible &&
          cursorShape == other.cursorShape &&
          cursorBlinking == other.cursorBlinking &&
          modeFlags == other.modeFlags &&
          displayOffset == other.displayOffset &&
          historySize == other.historySize &&
          scrollFraction == other.scrollFraction &&
          defaultFg == other.defaultFg &&
          defaultBg == other.defaultBg &&
          cursorColor == other.cursorColor &&
          full == other.full;
}
