// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine.dart';
import '../event_proxy.dart';
import '../frb_generated.dart';
import '../terminal_raster_present.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty_raster_frame`

TerminalEngine engineNew({
  required int columns,
  required int rows,
  required EngineConfig config,
}) => RustLib.instance.api.crateApiTerminalEngineNew(
  columns: columns,
  rows: rows,
  config: config,
);

Future<void> engineAdvance({
  required TerminalEngine engine,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalEngineAdvance(
  engine: engine,
  bytes: bytes,
);

Future<RenderUpdate> engineTakeDamage({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineTakeDamage(engine: engine);

/// Single FFI round-trip: parse PTY bytes then return damage (hot path).
Future<RenderUpdate> engineAdvanceAndTakeDamage({
  required TerminalEngine engine,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalEngineAdvanceAndTakeDamage(
  engine: engine,
  bytes: bytes,
);

List<EngineEvent> engineTakeEvents({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineTakeEvents(engine: engine);

RenderUpdate engineFullSnapshot({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineFullSnapshot(engine: engine);

void engineResize({
  required TerminalEngine engine,
  required int columns,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalEngineResize(
  engine: engine,
  columns: columns,
  rows: rows,
);

Future<RenderUpdate> engineScrollLines({
  required TerminalEngine engine,
  required int delta,
}) => RustLib.instance.api.crateApiTerminalEngineScrollLines(
  engine: engine,
  delta: delta,
);

/// Sub-cell pixel scroll. Positive `delta_px` scrolls up into history.
Future<RenderUpdate> engineScrollPixels({
  required TerminalEngine engine,
  required double deltaPx,
}) => RustLib.instance.api.crateApiTerminalEngineScrollPixels(
  engine: engine,
  deltaPx: deltaPx,
);

Future<RenderUpdate> engineScrollToBottom({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineScrollToBottom(engine: engine);

Future<RenderUpdate> engineScrollToTop({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineScrollToTop(engine: engine);

/// Absolute scroll position in lines (`0` = live bottom, `history_size` = top).
Future<RenderUpdate> engineScrollToOffset({
  required TerminalEngine engine,
  required double offsetLines,
}) => RustLib.instance.api.crateApiTerminalEngineScrollToOffset(
  engine: engine,
  offsetLines: offsetLines,
);

void engineClearHistory({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineClearHistory(engine: engine);

void engineSelectionStart({
  required TerminalEngine engine,
  required int displayRow,
  required int col,
  required bool rightHalf,
  required int kind,
}) => RustLib.instance.api.crateApiTerminalEngineSelectionStart(
  engine: engine,
  displayRow: displayRow,
  col: col,
  rightHalf: rightHalf,
  kind: kind,
);

void engineSelectionUpdate({
  required TerminalEngine engine,
  required int displayRow,
  required int col,
  required bool rightHalf,
}) => RustLib.instance.api.crateApiTerminalEngineSelectionUpdate(
  engine: engine,
  displayRow: displayRow,
  col: col,
  rightHalf: rightHalf,
);

void engineSelectionClear({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSelectionClear(engine: engine);

String? engineSelectionText({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSelectionText(engine: engine);

bool engineSearchSet({
  required TerminalEngine engine,
  required String pattern,
  required SearchOptions options,
}) => RustLib.instance.api.crateApiTerminalEngineSearchSet(
  engine: engine,
  pattern: pattern,
  options: options,
);

bool engineSearchNext({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSearchNext(engine: engine);

bool engineSearchPrev({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSearchPrev(engine: engine);

void engineSearchClear({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSearchClear(engine: engine);

bool engineSearchIsActive({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineSearchIsActive(engine: engine);

String? engineResolveHyperlink({
  required TerminalEngine engine,
  required int id,
}) => RustLib.instance.api.crateApiTerminalEngineResolveHyperlink(
  engine: engine,
  id: id,
);

RenderUpdate engineFullSnapshotSearched({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineFullSnapshotSearched(
      engine: engine,
    );

void engineRespondClipboardLoad({
  required TerminalEngine engine,
  required String text,
}) => RustLib.instance.api.crateApiTerminalEngineRespondClipboardLoad(
  engine: engine,
  text: text,
);

void engineSetCellPixels({
  required TerminalEngine engine,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiTerminalEngineSetCellPixels(
  engine: engine,
  width: width,
  height: height,
);

void engineReconfigure({
  required TerminalEngine engine,
  required EngineConfig config,
}) => RustLib.instance.api.crateApiTerminalEngineReconfigure(
  engine: engine,
  config: config,
);

/// Rust-raster present: consume damage and return RGBA + chrome (no LineUpdate
/// mirror payload). Dart uploads `rgba` to a retained `ui.Image`.
RasterPresentFrame engineTakeRasterPresent({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineTakeRasterPresent(
      engine: engine,
    );

/// Full viewport Rust-raster present (resize / explicit refresh).
RasterPresentFrame engineFullRasterPresent({required TerminalEngine engine}) =>
    RustLib.instance.api.crateApiTerminalEngineFullRasterPresent(
      engine: engine,
    );

/// Single FFI round-trip: parse PTY bytes then raster-present.
Future<RasterPresentFrame> engineAdvanceAndTakeRasterPresent({
  required TerminalEngine engine,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTerminalEngineAdvanceAndTakeRasterPresent(
  engine: engine,
  bytes: bytes,
);

Future<RasterPresentFrame> engineScrollLinesRaster({
  required TerminalEngine engine,
  required int delta,
}) => RustLib.instance.api.crateApiTerminalEngineScrollLinesRaster(
  engine: engine,
  delta: delta,
);

Future<RasterPresentFrame> engineScrollPixelsRaster({
  required TerminalEngine engine,
  required double deltaPx,
}) => RustLib.instance.api.crateApiTerminalEngineScrollPixelsRaster(
  engine: engine,
  deltaPx: deltaPx,
);

Future<RasterPresentFrame> engineScrollToBottomRaster({
  required TerminalEngine engine,
}) => RustLib.instance.api.crateApiTerminalEngineScrollToBottomRaster(
  engine: engine,
);

Future<RasterPresentFrame> engineScrollToTopRaster({
  required TerminalEngine engine,
}) => RustLib.instance.api.crateApiTerminalEngineScrollToTopRaster(
  engine: engine,
);

Future<RasterPresentFrame> engineScrollToOffsetRaster({
  required TerminalEngine engine,
  required double offsetLines,
}) => RustLib.instance.api.crateApiTerminalEngineScrollToOffsetRaster(
  engine: engine,
  offsetLines: offsetLines,
);
